local wanted_bees = {
    -- Allows creating the bee-bee gun for the assassin
    "careerbees.honey_smelter",
    -- Allows manual killing of queens (can we put a bee-bee gun in a mechanical user that is triggered if a queen exists in the apiary?)
    "careerbees.assassin",

    -- TODO: Determine what bees are useful for the playthrough

    -- All quest bees
    "extrabees.species.cyanite",
    "extrabees.species.blutonium",
    "careerbees.honey_smelter",
    "careerbees.acceleration",
    "careerbees.mad_scientist",
    "magicbees.speciesOsmium",
    "gendustry.bee.Springwater",
    "gendustry.bee.Gorgon",
    "gendustry.bee.Formic",
    "gendustry.bee.Balanced",
    "gendustry.bee.Agricultural",
    "gendustry.bee.Tinkerest",
    "gendustry.bee.Oxygen",
    "gendustry.bee.Alchemical",
    "gendustry.bee.Necronomibee",
    "gendustry.bee.Herblore",
    "gendustry.bee.Heraldry",
    "magicbees.speciesDraconic",
    "magicbees.speciesSkulking",
    "magicbees.speciesMysterious",
    "extrabees.species.acidic",
    "gendustry.bee.Crepuscular",
    "gendustry.bee.Sanitizing",
    "gendustry.bee.Flux",
    "gendustry.bee.Thorium",
    "gendustry.bee.Uranium",
    "gendustry.bee.Salty",
    "gendustry.bee.Pyramid",
    "gendustry.bee.Buried",
    "gendustry.bee.Controller",
    "gendustry.bee.Chevron",
    "gendustry.bee.Stargazer",
    "gendustry.bee.Ringbearer",
    "gendustry.bee.GunDevil",
    "gendustry.bee.Experienced",
    "forestry.speciesDemonic",
    "gendustry.bee.Fissile",
    "careerbees.cook",
    "careerbees.taxcollector",
    "gendustry.bee.Shyre",
    "gendustry.bee.Twilight",
    "careerbees.armorer",
    "gendustry.bee.Armored",
    "gendustry.bee.Trinity",
    "gendustry.bee.Sniper",
    "gendustry.bee.Gunman",
    "gendustry.bee.Bomber",
    "gendustry.bee.Artillery",
    "gendustry.bee.Gravity",
    "careerbees.sharpening",
    "gendustry.bee.Radiant",
    "gendustry.bee.Nucleartechnician",
    "gendustry.bee.Thermallyexpanded",
    "gendustry.bee.Serenading",
    "gendustry.bee.Deeplearner",
    "gendustry.bee.Apothecary",
    "gendustry.bee.Isekai",
    "gendustry.bee.Fluorine",
    "gendustry.bee.Helium",
    "gendustry.bee.Stormborn",
    "gendustry.bee.Ryleyan",
    "gendustry.bee.Soulsucking",
    "gendustry.bee.Darkness",
    "gendustry.bee.Fear",
    "gendustry.bee.Helplessness",
    "gendustry.bee.Solitude",
    "gendustry.bee.Warrior",
    "careerbees.energy",
}

return wanted_bees
